DECLARE
    V_PROFESOR PROFESOR;
    V_NOMBREPROF O_NOMBRE_COMPLETO := O_NOMBRE_COMPLETO('JOSE','MARTINEZ','HERNANDEZ');
    V_DIRECCIONPROF O_DOMICILIO := O_DOMICILIO('CALLE','FALSA',38,'5ºA');
    V_CPPROF O_CODIGO_POSTAL := O_CODIGO_POSTAL(47,193);
    V_ALUMNO ALUMNO;
BEGIN
    V_ALUMNO := NEW ALUMNO('1',O_NOMBRE_COMPLETO('MARIO','YUSTA','SILVA'),O_DOMICILIO('AVENIDA','POSTIGO',10,'1ºA'),O_CODIGO_POSTAL(41,001),'23/09/2004',10, 9, 8.5, 3.4);
    V_PROFESOR := NEW PROFESOR('2',V_NOMBREPROF,V_DIRECCIONPROF,V_CPPROF,'12/04/1998','23/09/2024');
    DBMS_OUTPUT.PUT_LINE(V_ALUMNO.CODIGO_DP);
    DBMS_OUTPUT.PUT_LINE(V_PROFESOR.CODIGO_DP);
END;
