ALTER TYPE O_DATOS_PERSONALES NOT FINAL;

CREATE TYPE PROFESOR UNDER O_DATOS_PERSONALES(
    F_INCORPORACION DATE
);

CREATE TYPE ALUMNO UNDER O_DATOS_PERSONALES(
    EVA1 NUMBER(4,2),
    EVA2 NUMBER(4,2),
    EVA3 NUMBER(4,2),
    EVA4 NUMBER(4,2)
);
