CREATE OR REPLACE TYPE O_CODIGO_POSTAL AS OBJECT(
    LOCALIDAD NUMBER(2),
    PROVINCIA NUMBER(3)
);
CREATE TYPE O_DOMICILIO AS OBJECT(
    TIPO_VIA VARCHAR(20),
    NOMBRE_VIA VARCHAR(20),
    NUMERO NUMBER(2),
    RESTO_DOMICILIO VARCHAR(50)
);
CREATE TYPE O_NOMBRE_COMPLETO AS OBJECT(
    NOMBRE VARCHAR(20),
    PR_APELLIDO VARCHAR(20),
    SG_APELLIDO VARCHAR(20)
);
CREATE OR REPLACE TYPE O_DATOS_PERSONALES AS OBJECT(
    CODIGO_DP VARCHAR(5),
    NOMBRE_COMPLETO O_NOMBRE_COMPLETO,
    DOMICILIO O_DOMICILIO,
    CODIGO_POSTAL O_CODIGO_POSTAL,
    FECHA_NACIMIENTO DATE
);
