DECLARE 
    POLI1 O_POLICIA;
    POLI2 O_POLICIA;
    POLI3 O_POLICIA;
    SALARIO_POLI1 NUMBER(6,2);
BEGIN
    POLI1 := NEW O_POLICIA('74835629H', 'Pedro', 'Lopez', 'Gracia', 632857351, 'LOCAL', 1500);
    POLI2 := NEW O_POLICIA('37329562O', 'Jaime', 'Hernadez', 'Diez', 637573623, 'NACIONAL', 1700);
    POLI3 := NEW O_POLICIA('85735295J', 'Luis', 'Dominguez', null, 621864736, 'OPERACIONES ESPECIALES', 1850);
    
    DBMS_OUTPUT.PUT_LINE(POLI1.TLF);
    DBMS_OUTPUT.PUT_LINE(POLI2.NOMBRE);
    DBMS_OUTPUT.PUT_LINE(POLI3.DNI ||' '|| POLI3.NOMBRE);
    
    SALARIO_POLI1 := POLI1.CALCULA_SALARIO(POLI1.SALARIO);
    DBMS_OUTPUT.PUT_LINE(SALARIO_POLI1);
    
    /*INSERT INTO POLICIA VALUES(POLI1);
    INSERT INTO POLICIA VALUES(POLI2);
    INSERT INTO POLICIA VALUES(POLI3);*/
    
    UPDATE POLICIA SET SALARIO = POLI1.CALCULA_SALARIO(POLI1.SALARIO)WHERE DNI = POLI1.DNI;
    UPDATE POLICIA SET SALARIO = POLI2.CALCULA_SALARIO(POLI2.SALARIO)WHERE DNI = POLI2.DNI;
    UPDATE POLICIA SET SALARIO = POLI3.CALCULA_SALARIO(POLI3.SALARIO)WHERE DNI = POLI3.DNI;
END;

DECLARE 
    INSPEC1 O_INSPECTOR;
    INSPEC2 O_INSPECTOR;
BEGIN
    INSPEC1 := NEW O_INSPECTOR('A14854312', 'Jamai', 'Marquez', 'Perez', 643876746, 'CRIMINOLOGIA');
    INSPEC2 := NEW O_INSPECTOR('75639674K', 'Marcos', 'Claro', 'Rubio', 654876756, 'ANTI-DROGA');
    
    INSERT INTO INSPECTOR VALUES(INSPEC1);
    INSERT INTO INSPECTOR VALUES(INSPEC2);
END;
