CREATE TYPE PERSONA AS OBJECT(
    DNI VARCHAR(9),
    NOMBRE VARCHAR(20),
    AP1 VARCHAR(30),
    AP2 VARCHAR(30),
    FECHA_NACIMIENTO DATE,
    MEMBER FUNCTION MUESTRA_EDAD RETURN NUMBER
);

CREATE OR REPLACE TYPE BODY PERSONA AS
MEMBER FUNCTION MUESTRA_EDAD RETURN NUMBER IS
    FECHA_ACTUAL DATE;
    BEGIN
        FECHA_ACTUAL := SYSDATE;
        RETURN TO_NUMBER(TO_CHAR(FECHA_ACTUAL, 'YYYY')) - TO_NUMBER(TO_CHAR(SELF.FECHA_NACIMIENTO,'YYYY'));
    END;
END;

DECLARE
    PER1 PERSONA;
    EDAD NUMBER;
BEGIN
    PER1 := NEW PERSONA('12437015H', 'MARIO', 'YUSTA','SILVA', '23/09/2004');
    EDAD := PER1.MUESTRA_EDAD();
    DBMS_OUTPUT.PUT_LINE(EDAD);
END;
