CREATE TYPE PERSONA2 AS OBJECT(
    NOMBRE VARCHAR2(20),
    APELLIDOS VARCHAR2(30),
    FECHA_NACIMIENTO DATE,
    CONSTRUCTOR FUNCTION C_PERSONA(NOMBRE VARCHAR2, APELLIDOS VARCHAR2, FECHA_NACIMIENTO DATE)
    RETURN SELF AS RESULT);
    
CREATE OR REPLACE TYPE BODY C_PERSONA AS
CONSTRUCTOR FUNCTION C_PERSONA(
    NOMBRE VARCHAR2,
    APELLIDOS VARCHAR2,
    FECHA_NACIMIENTO DATE
) RETURN SELF AS RESULT IS
    V_EDAD NUMBER(2);
    BEGIN
        SELF.NOMBRE := NOMBRE;
        SELF.APELLIDOS := APELLIDOS;
        SELF.FECHA_NACIMIENTO := FECHA_NACIMIENTO;
        DBMS_OUTPUT.PUT_LINE(NOMBRE);
        RETURN;
    END;
END;
