CREATE TYPE O_EMPLEADO AS OBJECT(
    DNI VARCHAR(9),
    NOMBRE VARCHAR(20),
    AP1 VARCHAR(20),
    AP2 VARCHAR(20),
    TLF NUMBER(9)
)NOT FINAL;

CREATE TYPE O_INSPECTOR UNDER O_EMPLEADO(
    ESPECIALIDAD VARCHAR(30)
);

CREATE TYPE O_POLICIA UNDER O_EMPLEADO(
    CATEGORIA VARCHAR(20),
    SALARIO NUMBER(6,2),
    MEMBER FUNCTION CALCULA_SALARIO(SALARIOBASE NUMBER) RETURN NUMBER
);  

ALTER TYPE O_POLICIA MODIFY ATTRIBUTE CATEGORIA VARCHAR(30);

CREATE OR REPLACE TYPE BODY O_POLICIA AS
    MEMBER FUNCTION CALCULA_SALARIO( 
        SALARIOBASE NUMBER
    )RETURN NUMBER IS
    SALARIOTOTAL NUMBER(6,2);
        BEGIN
            IF UPPER(SELF.CATEGORIA) = 'LOCAL' THEN
                SALARIOTOTAL := SALARIOBASE *1.05;
            ELSIF UPPER(SELF.CATEGORIA) = 'NACIONAL' THEN
                SALARIOTOTAL := SALARIOBASE *1.15;
            ELSIF UPPER(SELF.CATEGORIA) = 'OPERACIONES ESPECIALES' THEN
                SALARIOTOTAL := SALARIOBASE *1.2;
            END IF;
            
            RETURN SALARIOTOTAL;
        END;
END;

CREATE TABLE POLICIA OF O_POLICIA;
CREATE TABLE INSPECTOR OF O_INSPECTOR;
