SET SERVEROUTPUT ON;

DECLARE
V_CODIGO_POSTAL O_CODIGO_POSTAL := O_CODIGO_POSTAL(41,001);
V_DOMICILIO O_DOMICILIO := O_DOMICILIO('AVENIDA','POSTIGO',10,'1ºA');
V_NOMBRE O_NOMBRE_COMPLETO := O_NOMBRE_COMPLETO('ANGELA', 'NEGRO', 'CASTILLA');
V_DATOS_PERSONALES O_DATOS_PERSONALES := O_DATOS_PERSONALES('001A', V_NOMBRE,V_DOMICILIO, V_CODIGO_POSTAL, '18/04/1983');
BEGIN
DBMS_OUTPUT.PUT_LINE(V_DATOS_PERSONALES.codigo_postal.LOCALIDAD);
END;
